version: '2'

services:

  nginx:
    build: ./nginx
    image: ark-nginx
    container_name: ark-nginx-run
    depends_on:
      - node
    volumes:
      - /etc/docker/nginx/vhost:/etc/nginx/vhost
    ports:
      - '80:80'

  node:
    build: ./node
    image: ark-node
    container_name: ark-node-run
    volumes:
      - /home/app:/app
    ports:
      - '8080-8090'

  ci:
    build: ./gitlab-ci-runner
    image: ark-ci

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker/gitlab-runner:/etc/gitlab-runner
