
version: '2'

services:

  nginx:
    build: ./nginx
    image: vk-nginx
    container_name: vk-nginx-run
    depends_on:
      - node
    ports:
      - '80:80'

  node:
    build: ./node
    image: vk-node
    container_name: vk-node-run
    volumes:
      - /home/apps:/apps
    ports:
      - '8080'
