concurrent = 1
check_interval = 0

[[runners]]
  name = "aliyun-node-ci"
  url = "https://gitlab.com/ci"
  token = "xxx"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "ark-ci"
    privileged = false
    disable_cache = false
    volumes = ["/cache", "/home/app:/app"]
    pull_policy = 'if-not-present'
  [runners.cache]
